services:
  frontend:
    build:
      context: ./frontend
      dockerfile: config/docker/dev.Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:${API_PORT}
