services:
  frontend:
    build:
      context: ./frontend
      dockerfile: config/docker/Dockerfile
      args:
        VITE_API_URL: ${API_BASEURL} # Pass build-time variable for API URL
    container_name: frontend
    restart: always
    environment:
      - VITE_API_URL=${API_BASEURL}
    expose: [3000]
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/public:/usr/share/caddy/public:ro
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: ./backend
      dockerfile: deploy/Dockerfile
    container_name: backend
    restart: on-failure:3
    env_file:
      - backend/deploy/.env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: database
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

volumes:
  postgres_data:
