services:
  frontend:
    build:
      context: ./frontend
      dockerfile: config/docker/Dockerfile
      args:
        VITE_API_URL: ${API_BASEURL} # Pass build-time variable for API URL
    container_name: template-frontend
    restart: always
    environment:
      - VITE_API_URL=${API_BASEURL}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/public:/usr/share/caddy/public:ro
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: ./backend
      dockerfile: deploy/Dockerfile
    container_name: template-backend
    restart: on-failure:3
    env_file:
      - backend/deploy/.env
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "weak"
      POSTGRES_DB: "backend_db"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

volumes:
  postgres_data:
