definitions:
  models.UserChangePWD:
    properties:
      id:
        type: integer
      newPassword:
        type: string
    type: object
  models.UserCreate:
    properties:
      email:
        type: string
      name:
        type: string
      pwd:
        type: string
      sur_name:
        type: string
    type: object
  models.UserLogin:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
paths:
  /user/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: UserID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully get user
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get user
      tags:
      - user
  /user/change/pwd:
    put:
      consumes:
      - application/json
      parameters:
      - description: change password
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.UserChangePWD'
      produces:
      - application/json
      responses:
        "200":
          description: Success changing
          schema:
            type: integer
        "400":
          description: Invalid id
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Change password
      tags:
      - user
  /user/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: user create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.UserCreate'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created user
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create user
      tags:
      - user
  /user/delete/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: UserID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully deleted
          schema:
            type: integer
        "400":
          description: Invalid id
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete user
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: user login
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully login user
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login user
      tags:
      - user
swagger: "2.0"
